import React, { useState,useEffect } from 'react'
import '../../../css/Report.css'
import grid from '../../../asset/img/gridbox.png'
import download from '../../../asset/img/download.png'
import Cookies from 'universal-cookie';
import share from '../../../asset/img/share.png'
import {getImformation} from '../../../store/action/ProfileAction'
import cross from '../../../asset/img/cross.png'
import { Card } from 'react-bootstrap'
import Monthly from './Monthly'
import { useDispatch, useSelector } from "react-redux";
import { useNavigate } from 'react-router-dom';
import Weekly from './Weekly';
import Yearly from './Yearly';
const cookies = new Cookies();
function ReportTable() {
  const Dispatch = useDispatch();
  const navigate = useNavigate();
  const [state1, setstate1] = useState(false)
  const [state2, setstate2] = useState(false)
  const [state3, setstate3] = useState(false)
  const getInformationReducer = useSelector((state) => state.getInformationReducer)
  const Fname = useState(
    getInformationReducer && getInformationReducer.allUserData && getInformationReducer.allUserData.data && getInformationReducer.allUserData.data.user && getInformationReducer.allUserData.data.user.firstName
  )
  const Lname = useState(
    getInformationReducer && getInformationReducer.allUserData && getInformationReducer.allUserData.data && getInformationReducer.allUserData.data.user && getInformationReducer.allUserData.data.user.lastName
  )
  const gender = useState(
    getInformationReducer && getInformationReducer.allUserData && getInformationReducer.allUserData.data && getInformationReducer.allUserData.data.user && getInformationReducer.allUserData.data.user.gender
  )
  let check=(gender[0])
  // console.log(check)
  const [genderNew,setGenderNew]=useState("")
  useEffect(() => {
    if (!cookies.get('ddAdminToken')) {
      navigate("/");
    }
    if(check=="F" || check=="f"){
     setGenderNew("Female") 
    }else if(check=="M" || check=="m"){
      setGenderNew("Male")
    }else{
      setGenderNew("Other")
    }
    Dispatch(getImformation());
  }, [genderNew]);

  

  return (

    <div className='report-form-div '>
      {state1 && (<div >
        <Card className='cardreport'>
          <div style={{
            display: 'flex', boxShadow: '2px 2px 5px grey', backgroundColor: '#353656',
            borderRadius: '5px',
          }}>
            <img
              style={{ margin: '2% 1% 2% 70%', width: '40px', height: '40px' }}
              src={download}
            />
            <img
              style={{ margin: '2% 1% 2% 1%', width: '40px', height: '40px' }}
              src={share}
            />
            <img
              style={{ margin: '2% 1% 2% 1%', width: '40px', height: '40px' }}
              src={cross}
              onClick={() => setstate1(!state1)}
            />
          </div>
          <h2 style={{ margin: '5% 0% 2% 25%', fontSize: '30px', }}>Insulin Report Monthy</h2>
          <div style={{
            display: 'flex', height: '100%',

          }}>
            <p style={{ margin: '2% 15% 0% 5%' }}>Export Date &nbsp;&nbsp; &nbsp;10/2/23</p>
            <p style={{ margin: '2% 0%' }}>Patient Name : {Fname} {Lname}</p>

          </div>
          <div style={{
            display: 'flex', height: '100%',

          }}>
            <p style={{ margin: '2% 12% 0% 5%' }}>Accession No : 10223213</p>
            <p style={{ margin: '2% 0%' }}>Age: 22</p>

          </div>
          <div>
            <p style={{ margin: '2% 0% 0% 48%' }}>Gender : {genderNew}</p>
          </div>
          <div >
            <p style={{ margin: '2% 12% 1% 5%', fontSize: '20px' }}>Reported on</p>
            <p style={{ margin: '2% 0% 2% 5%', }} >Monthy</p>
          </div>
         <Monthly/>
          <p style={{ margin: '2% 0% 0% 5%' }}>lorem</p>
          <p style={{ margin: '2% 0% 0% 5%' }}>F:</p>
          <p style={{ margin: '2% 0% 0% 5%' }}>N:</p>
          <p style={{ color: 'gray', fontSize: '15px', margin: '15% 0% 1% 20%' }}>Digitially Generated By <spam style={{ color: '#cb297b' }}>AgVa</spam> <spam style={{ color: '#444444' }}>HealthCare</spam></p>
        </Card>

      </div>
      )}
      {state2 && (<div >
        <Card className='bolus-card'>
          <div style={{
            display: 'flex', boxShadow: '2px 2px 5px grey', backgroundColor: '#353656',
            borderRadius: '5px',
          }}>
            <img
              style={{ margin: '2% 1% 2% 70%', width: '40px', height: '40px' }}
              src={download}
            />
            <img
              style={{ margin: '2% 1% 2% 1%', width: '40px', height: '40px' }}
              src={share}
            />
            <img
              style={{ margin: '2% 1% 2% 1%', width: '40px', height: '40px' }}
              src={cross}
              onClick={() => setstate2(!state2)  } 
             
            />
          </div>
         
            <h2 style={{ margin: '5% 0% 2% 25%', fontSize: '30px', }}>Insulin Report Weekly </h2>
            <div style={{
            display: 'flex', height: '100%',

          }}>
            <p style={{ margin: '2% 15% 0% 5%' }}>Export Date &nbsp;&nbsp; &nbsp;10/2/23</p>
            <p style={{ margin: '2% 0%' }}>Patient Name : {Fname} {Lname}</p>

          </div>
          <div style={{
            display: 'flex', height: '100%',

          }}>
            <p style={{ margin: '2% 12% 0% 5%' }}>Accession No : 10223213</p>
            <p style={{ margin: '2% 0%' }}>Age: 22</p>

          </div>
          <div>
            <p style={{ margin: '2% 0% 0% 48%' }}>Gender : {genderNew}</p>
          </div>
          <div >
            <p style={{ margin: '2% 12% 1% 5%', fontSize: '20px' }}>Reported on</p>
            <p style={{ margin: '2% 0% 2% 5%', }}>Weekly</p>
          </div>
         <Weekly/>
          <p style={{ color: 'gray', fontSize: '15px', margin: '35% 0% 1% 20%' }}>Digitially Generated By <spam style={{ color: '#cb297b' }}>AgVa</spam> <spam style={{ color: '#444444' }}>HealthCare</spam></p>
        </Card>

      </div>
      )}
      {state3 && (<div >
        <Card className='bolus-card'>
          <div style={{
            display: 'flex', boxShadow: '2px 2px 5px grey', backgroundColor: '#353656',
            borderRadius: '5px',
          }}>
            <img
              style={{ margin: '2% 1% 2% 70%', width: '40px', height: '40px' }}
              src={download}
            />
            <img
              style={{ margin: '2% 1% 2% 1%', width: '40px', height: '40px' }}
              src={share}
            />
            <img
              style={{ margin: '2% 1% 2% 1%', width: '40px', height: '40px' }}
              src={cross}
              onClick={() => setstate3(!state3)}
            />
          </div>
          
            <h2 style={{ margin: '5% 0% 2% 25%', fontSize: '30px', }}>Insulin Report Yearly</h2>

            <div style={{
            display: 'flex', height: '100%',

          }}>
            <p style={{ margin: '2% 15% 0% 5%' }}>Export Date &nbsp;&nbsp; &nbsp;10/2/23</p>
            <p style={{ margin: '2% 0%' }}>Patient Name : {Fname} {Lname}</p>

          </div>
          <div style={{
            display: 'flex', height: '100%',

          }}>
            <p style={{ margin: '2% 12% 0% 5%' }}>Accession No : 10223213</p>
            <p style={{ margin: '2% 0%' }}>Age: 22</p>

          </div>
          <div>
            <p style={{ margin: '2% 0% 0% 48%' }}>Gender : {genderNew}</p>
          </div>
          <div >
            <p style={{ margin: '2% 12% 1% 5%', fontSize: '20px' }}>Reported on</p>
            <p style={{ margin: '2% 0% 2% 5%', }} >Yearly</p>
          </div>
         <Yearly/>
          <p style={{ color: 'gray', fontSize: '15px', margin: '35% 0% 1% 20%' }}>Digitially Generated By <spam style={{ color: '#cb297b' }}>AgVa</spam> <spam style={{ color: '#444444' }}>HealthCare</spam></p>
        </Card>

      </div>
      )}
      <h1>Report</h1>
      <div style={{ display: 'flex' }}>
        <div className='report-div'>
          <h1 className='report-title'>Monthy Report</h1>
          <h6 className='date-tag'>Last Generated</h6>
          <img
            className='Grid'
            src={grid}
            onClick={() => setstate1(!state1)}
          />
        </div>
        <div className='report-div'>
          <h1 className='report-title'>Weekly Report</h1>
          <h6 className='date-tag'>Last Generated</h6>
          <img
            className='Grid'
            src={grid}
            onClick={() => setstate2(!state2)}
          />
        </div>

      </div>
      <div className='report-div'>
        <h1 className='report-title'> Yearly Report</h1>
        <h6 className='date-tag'> Last Generated</h6>
        <img
          className='Grid'
          src={grid}
          onClick={() => setstate3(!state3)}
        />
      </div>


    </div>


  )
}

export default ReportTable
