import React,{useState} from 'react'
import '../../../css/Report.css'
import grid from '../../../asset/img/gridbox.png'
import download from '../../../asset/img/download.png'
import share from '../../../asset/img/share.png'
import cross from '../../../asset/img/cross.png'
import { Card } from 'react-bootstrap'
function ReportTable() {
    const [state1, setstate1] = useState(false)
    const [state2, setstate2] = useState(false)
    const [state3, setstate3] = useState(false)
   
  return (
   
    <div className='report-form-div '>
         {state1 && (<div >
                <Card className='bolus-card'>
                    <div style={{
                        display: 'flex', boxShadow: '2px 2px 5px grey',backgroundColor:'#353656',
                        borderRadius: '5px',
                    }}>
                        <img
                        style={{margin:'2% 1% 2% 70%',width:'40px',height:'40px'}}
                          src={download}
                        />
                        <img
                         style={{margin:'2% 1% 2% 1%',width:'40px',height:'40px'}}
                          src={share}
                        />
                        <img
                          style={{margin:'2% 1% 2% 1%',width:'40px',height:'40px'}}
                          src={cross}
                          onClick={()=>setstate1(!state1)}
                        />
                    </div>
                    <div style={{
                        display: 'flex',  height: '100%',
                        
                    }}>
                        <h2 style={{margin:'5% 0% 2% 30%', fontSize: '30px', }}>Insulin Report Monthy</h2>
                      
                    </div>
                    <p style={{ color: 'gray', fontSize: '15px',  margin: '35% 0% 1% 20%' }}>Digitially Generated By <spam style={{ color: '#cb297b' }}>AgVa</spam> <spam style={{ color: '#444444' }}>HealthCare</spam></p>
                </Card>

            </div>
            )}
            {state2 && (<div >
                <Card className='bolus-card'>
                    <div style={{
                        display: 'flex', boxShadow: '2px 2px 5px grey',backgroundColor:'#353656',
                        borderRadius: '5px',
                    }}>
                        <img
                        style={{margin:'2% 1% 2% 70%',width:'40px',height:'40px'}}
                          src={download}
                        />
                        <img
                         style={{margin:'2% 1% 2% 1%',width:'40px',height:'40px'}}
                          src={share}
                        />
                        <img
                          style={{margin:'2% 1% 2% 1%',width:'40px',height:'40px'}}
                          src={cross}
                          onClick={()=>setstate2(!state2)}
                        />
                    </div>
                    <div style={{
                        display: 'flex',  height: '100%',
                        
                    }}>
                        <h2 style={{margin:'5% 0% 2% 30%', fontSize: '30px', }}>Insulin Report Weekly </h2>
                      
                    </div>
                    <p style={{ color: 'gray', fontSize: '15px',  margin: '35% 0% 1% 20%' }}>Digitially Generated By <spam style={{ color: '#cb297b' }}>AgVa</spam> <spam style={{ color: '#444444' }}>HealthCare</spam></p>
                </Card>

            </div>
            )}
            {state3 && (<div >
                <Card className='bolus-card'>
                    <div style={{
                        display: 'flex', boxShadow: '2px 2px 5px grey',backgroundColor:'#353656',
                        borderRadius: '5px',
                    }}>
                        <img
                        style={{margin:'2% 1% 2% 70%',width:'40px',height:'40px'}}
                          src={download}
                        />
                        <img
                         style={{margin:'2% 1% 2% 1%',width:'40px',height:'40px'}}
                          src={share}
                        />
                        <img
                          style={{margin:'2% 1% 2% 1%',width:'40px',height:'40px'}}
                          src={cross}
                          onClick={()=>setstate3(!state3)}
                        />
                    </div>
                    <div style={{
                        display: 'flex',  height: '100%',
                        
                    }}>
                        <h2 style={{margin:'5% 0% 2% 30%', fontSize: '30px', }}>Insulin Report Yearly</h2>
                      
                    </div>
                    <p style={{ color: 'gray', fontSize: '15px',  margin: '35% 0% 1% 20%' }}>Digitially Generated By <spam style={{ color: '#cb297b' }}>AgVa</spam> <spam style={{ color: '#444444' }}>HealthCare</spam></p>
                </Card>
               
            </div>
            )}  
      <h1>Report</h1>
      <div style={{display:'flex'}}>
      <div className='report-div'>
        <h1 className='report-title'>Monthy Report</h1>
        <h6 className='date-tag'>Last Generated</h6>
         <img
            className='Grid'
            src={grid}
            onClick={()=>setstate1(!state1)}
         />
      </div>
      <div className='report-div'>
        <h1 className='report-title'>Weekly Report</h1>
        <h6 className='date-tag'>Last Generated</h6>
        <img
            className='Grid'
            src={grid}
            onClick={()=>setstate2(!state2)}
         />
      </div>
      
      </div>
      <div className='report-div'>
        <h1 className='report-title'> Yearly Report</h1>
        <h6 className='date-tag'> Last Generated</h6>
        <img
            className='Grid'
            src={grid}
            onClick={()=>setstate3(!state3)}
         />
      </div>

     
    </div>
   

  )
}

export default ReportTable
