//Today reading chart
export const TODAYREADING_FAIL = "TODAYREADING_FAIL"
export const TODAYREADING_REQUEST = "TODAYREADING_REQUEST"
export const TODAYREADING_SUCCESS = "TODAYREADING_SUCCESS"

//Avg insulin weekly
export const AVGFROMDATERANGE_FAIL = "AVGFROMDATERANGE_FAIL"
export const AVGFROMDATERANGE_REQUEST = "AVGFROMDATERANGE_REQUEST"
export const AVGFROMDATERANGE_SUCCESS = "AVGFROMDATERANGE_SUCCESS"

//Avg insulin previous week
export const PREVWEEKRANGE_FAIL = "PREVWEEKRANGE_FAIL"
export const PREVWEEKRANGE_REQUEST = "PREVWEEKRANGE_REQUEST"
export const PREVWEEKRANGE_SUCCESS = "PREVWEEKRANGE_SUCCESS"

//Battery, Reservoir
export const DEVICE_DATA_FAIL='DEVICE_DATA_FAIL'
export const DEVICE_DATA_REQUEST='DEVICE_DATA_REQUEST'
export const DEVICE_DATA_SUCCESS='DEVICE_DATA_SUCCESS'

//Insulin , Glucose
export const GET_READING_FAIL='GET_READING_FAIL'
export const GET_READING_REQUEST='GET_READING_REQUEST'
export const GET_READING_SUCCESS='GET_READING_SUCCESS'