//Getting User Imformation
export const GETIMFOTMATION_FAIL = "GETIMFOTMATION_FAIL"
export const GETIMFOTMATION_REQUEST = "GETIMFOTMATION_REQUEST"
export const GETIMFOTMATION_SUCCESS = "GETIMFOTMATION_SUCCESS"

//Update User Imformation
export const UPDATEIMFORMATION_FAIL = "UPDATEIMFORMATION_FAIL"
export const UPDATEIMFORMATION_REQUEST = "UPDATEIMFORMATION_REQUEST"
export const UPDATEIMFORMATION_SUCCESS = "UPDATEIMFORMATION_SUCCESS"
